version: '3.8'

services:
  db:
    image: postgres:13
    container_name: bookstore-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-bookstore_db}
    ports:
      - "${DB_PORT:-5432}:${DB_PORT:-5432}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bookstore_network

  redis:
    image: redis:latest
    container_name: redis-cache
    restart: always
    ports:
      - "${SPRING_DATA_REDIS_PORT:-6379}:${SPRING_DATA_REDIS_PORT:-6379}"
    command: redis-server --port ${SPRING_DATA_REDIS_PORT:-6379} --bind 0.0.0.0
    environment:
      REDIS_PASSWORD: ${SPRING_DATA_REDIS_PASSWORD:-password}
    volumes:
      - redis_data:/data
    networks:
      - bookstore_network

  api:
    build: .
    container_name: bookstore-api
    depends_on:
      - db
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-docker}
    ports:
      - "${API_PORT:-8080}:${API_PORT:-8080}"
    networks:
      - bookstore_network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  bookstore_network:
    driver: bridge
